<a href="https://colab.research.google.com/github/AFDBILLIONS/AMapPoi/blob/master/NumPy_Part1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

##NumPy

Numpy is the core library for scientific computing in Python. It provides a high-performance multidimensional array object, and tools for working with these arrays. If you are already familiar with MATLAB, you might find this tutorial useful to get started with Numpy.

In [ ]:
#Install NumPy
!pip install numpy

To use Numpy, we first need to import the numpy package:

In [ ]:
#Import NumPy
import numpy as np

###Basics

In [8]:
#Create NumPy 1D array
a = np.array([1,2,3], dtype='int32')
print(a)


[1 2 3]


In [9]:
#Create NumPy 2D array
b = np.array([
              [9.0, 8.0, 7.0],
              [6.0, 5.0, 4.0]
]   
)
print(b)

[[9. 8. 7.]
 [6. 5. 4.]]


In [ ]:
# Get Dimension
print(a.ndim)
print(b.ndim)


1
2


In [10]:
# Get Shape (r,c)
print(a.shape)
print(b.shape)



(3,)
(2, 3)


In [ ]:
# Get Type
print(a.dtype)
print(b.dtype)

int32
float64


In [ ]:
# Get number of elements
print(a.size)
print(b.size)



3
6


### Accessing/Changing specific elements, rows, columns, etc

In [ ]:
a = np.array([
              [1,2,3,4,5,6,7],
              [8,9,10,11,12,13,14]])
print(a)

[[ 1  2  3  4  5  6  7]
 [ 8  9 10 11 12 13 14]]


In [ ]:
# Get a specific element [r, c]
print(a[1,5])



13


In [ ]:
# Get a specific row 
print(a[0,:])



[1 2 3 4 5 6 7]


In [ ]:
# Get a specific column
print(a[:, 2])


[ 3 10]


In [ ]:
# Getting a little more fancy [startindex:endindex:stepsize]
print(a[0,1:-1:2])

[2 4 6]


In [ ]:
##Some More
a[1,5] = 20
print(a)

[[ 1  2  3  4  5  6  7]
 [ 8  9 10 11 12 20 14]]


In [ ]:
a[:,2] = [1, 2]
print(a)

[[ 1  2  1  4  5  6  7]
 [ 8  9  2 11 12 20 14]]


###QUIZ!!!

#### 3D Example

In [ ]:
b = np.array([
              [[1,2],[3,4]],
              [[5,6],[7,8]]
              ])
print(b)

[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]


In [ ]:
# Get specific element (work outside in)
print(b[0, 1, 1])


4


Numpy also provides many functions to create arrays:

In [ ]:
# Create an array of all zeros
a = np.zeros((2, 3))
print(a)


[[0. 0. 0.]
 [0. 0. 0.]]


In [ ]:
# Create an array of all ones
b = np.ones((4,3))
print(b)


[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]


In [ ]:
# Create a constant array
c = np.full((3,2), 7)
print(c)


[[7 7]
 [7 7]
 [7 7]]


In [ ]:
# Create a 4x4 identity matrix
d = np.eye(4)
print(d)


[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]


In [ ]:
# Create an array filled with random values
e = np.random.random((2,2))
print(e)



[[0.36908372 0.17535938]
 [0.05679538 0.37964783]]



####Be careful when copying arrays!!!

In [ ]:
#Your Code Here
a = np.array([1,2,3])
b = a.copy()
b[0] = 100
print(a)



[1 2 3]


###QUIZ!!!

### Array Math

In [ ]:
a = np.array([1,2,3,4])
print(a)

[1 2 3 4]


In [ ]:
#Addition
print(a+1)


[2 3 4 5]


In [ ]:
#Subtraction
print(a-2)


[-1  0  1  2]


In [ ]:
#Multiplication
print(a*2)



[2 4 6 8]


In [ ]:
#Division
print(a/2)

[0.5 1.  1.5 2. ]


In [ ]:
#Exponent

print(a**2)

[ 1  4  9 16]


In [ ]:
# Take the sin
print(np.sin(a))


[ 0.84147098  0.90929743  0.14112001 -0.7568025 ]


####Basic mathematical functions operate elementwise on arrays, and are available both as operator overloads and as functions in the numpy module:

In [ ]:
#Create 2D array x and y
x = np.array([
              [1, 2],
              [3, 4]
])
y = np.array([
            [5,6],
            [7,8]  
])
print(x)
print(y)




[[1 2]
 [3 4]]
[[5 6]
 [7 8]]


In [ ]:
# Elementwise sum; both produce the array
print(x+y)
print(np.add(x,y))


[[ 6  8]
 [10 12]]
[[ 6  8]
 [10 12]]


In [ ]:
# Elementwise difference; both produce the array

print(x-y)
print(np.subtract(x, y))

[[-4 -4]
 [-4 -4]]
[[-4 -4]
 [-4 -4]]


In [ ]:
# Elementwise product; both produce the array
print(x*y)
print(np.multiply(x,y))


[[ 5 12]
 [21 32]]
[[ 5 12]
 [21 32]]


In [ ]:
# Elementwise division; both produce the array
print(x/y)
print(np.divide(x,y))


[[0.2        0.33333333]
 [0.42857143 0.5       ]]
[[0.2        0.33333333]
 [0.42857143 0.5       ]]


In [ ]:
# Elementwise square root; produces the array
print(np.sqrt(x))



[[1.         1.41421356]
 [1.73205081 2.        ]]


###QUIZ!!!

#Thank You!